### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by wedstrijdsecretaris** [thor-it/Teamsite-Public#10]
Members that update their website, cannot use their old credentials (2 mentions)

**Comment by davidzwa** [comment]
Thanks for the report. So a bit of explanation what I've seen happening now:
- user opens the app
- it does not update or it updates too late, because of some reason (I saw this on iOS) 
- they try to login not knowing its the old app and that is rejected
- the message they get is "this user/password isnt know" but what actually should be shown is "the app isnt up to date".

**Solutions**
- Refresh the app by dragging it down (wont work on iOS)
- Delete the app and download again (works most of the time)
- Clean the browser cache or press Control + F5 / Command + F5 to force a reload

Please shoot me a PM and I can also guide the users you mention as talking them through fixes it always
